travis:
  secure:
    BINSTAR_TOKEN: Rwm3rVruV5Hzda7mZwtMDBMB7c+jNHZ+26YDL8vsxCM4tRf7jqnX2YXecDfK98izbW5N+NLkUGBzXzMV6+ItnrDemvk6nOMoqFT/vuFG6/ZQq3MQzNGAstpg/P+rgFYB4KNWlGm3ffIf19kvHuWASxddyvQrPLHolxiMX1tSslhcZGveu/uGEt+Ogw5s1UfNxHCbPJ9Zk2VM2TASfAIqaRchwNpz4QNJEGJtm8ZCaiOE0QDswSML9bssKkFc72xtEu4BWNOhlNwH/UGfigfBNrAWRjVElaMiEcOYrHTFE+1qdAjuwysCFtJCEghT3LlZ/RR0H1kCrI4N0Fc7fvttVuN0YufG4n4chrpg7SmF7O5poiRE0n4wCZ2kIoJw8qvknT9TG+ohlwA9r4GWLGcT/fLE8T5D2VFflwexwd8/SXNpXST4ZkAlMtpACkphS2+C/m5TuEKfQYW+199ftq4EVVduDUT4dstByRVb0eK5eVVx9APpaxDy6aQhGa/Y91844b1nf9kD7wsSUyq7I769oRcNpOvhHilVcp8+XC2BticW4gTojCSqkR68kVDaa0lFm8DG0ILAwfJXfcyLL5ftbLAQXWOotDzX9JK0GVL5oerucju1c+Cgddnj9/Z/ACcnV6TcfawL4I1wGgN8ipZEXLxw3AC+ZdJWP/foGauWPkE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
