travis:
  secure:
    BINSTAR_TOKEN: TTuZxDfbEI+Vf18EZoEIYRtvuqrlaCAarpUF3cTvXFW53lBLncZeBcj0bCxitI8CCUIryUdYvGnQVTDBWTIjh60hTcp/1c/ScEkHsEKlcT0mPeS5uv1p8J5WEZQ9CUXQ7mu7hA1wZi2oHbQGSRsCp1dQ9pygov8pFDoh2XQeKqPEDnokC7GtIEXEfqBiTYvJ6DwAkGbWxLX0gS6vdCBy9AtHri2oVAM5J8noMBH8cJwAPI5LdHO/iSEtjeq+3jF4k/NC2sA0I3BrZWPTeN2LH+1pwKA7J06V6LVeNvZZ+Ud1j6qsVGL6J3wkqAqbTwLUKKy44PpjcHqhbftEuEq20eQvdGDyAd1U/21nQkJ/k8Nb+EjVSDBnKK5rhnNkUAlKuKZALEcKYof5649upib9KgnS1MrTcNi/n9Ze00I5MkSRdV7p0QjCt0vF7FvCC1LIcOMjJdIHSF77icTtbB1F+VruR3OBXJOGTZ7UFdHvRw5Ytb+WFvTB5crK0/hYWrYDii4oTvIvJRK00sofUUAmovGCEWfrM6dijwDzyIAIvGtVM/qelLeU49ai39bdbW+sqPj1U4tLIk5J0Fy3Cxjm/DlIuLi52hHSE0wW7OpQAFKhFLvbxZMB8Ysmw9Z3NuNhM9YUl0aGiAb4vYy+jFhx76LBHN6dQUktrL7ukEWYW/A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
